# Generated by Django 5.0.6 on 2024-12-05 12:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('category', models.CharField(choices=[('entertainment', 'Entertainment'), ('lifestyle', 'Lifestyle'), ('politics', 'Politics'), ('travel', 'Travel'), ('sports', 'Sports'), ('technology', 'Technology'), ('health', 'Health'), ('science', 'Science')], default='lifestyle', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('failed', 'Generation Failed')], default='draft', max_length=20)),
                ('image_url', models.URLField(blank=True, help_text='Main image URL for the blog post', null=True, verbose_name='Featured Image')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'created_at'], name='transcriber_categor_5f15f1_idx'), models.Index(fields=['slug'], name='transcriber_slug_39dc4b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='products/images/')),
                ('keywords', models.TextField(help_text='Comma-separated keywords for matching posts')),
                ('description', models.TextField(blank=True, null=True)),
                ('affiliate_link', models.URLField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('blogPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='transcriber.blogpost')),
            ],
        ),
    ]
