# Generated by Django 5.0.6 on 2024-12-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriber', '0002_affiliateproduct_blogpostproductrecommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('affiliate_link', models.URLField()),
                ('image_url', models.URLField()),
                ('keywords', models.TextField()),
                ('category', models.CharField(choices=[('entertainment', 'Entertainment'), ('lifestyle', 'Lifestyle'), ('politics', 'Politics'), ('travel', 'Travel'), ('sports', 'Sports'), ('technology', 'Technology'), ('health', 'Health'), ('science', 'Science')], default='lifestyle', max_length=20)),
            ],
        ),
    ]
