# Generated by Django 5.1.4 on 2024-12-29 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcriber', '0003_affiliateitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AffiliateItem',
        ),
        migrations.RemoveField(
            model_name='product',
            name='blogPost',
        ),
        migrations.DeleteModel(
            name='BlogPostProductRecommendation',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
